pub const SPV_HEADER_LENGTH: usize = 5;
pub const SPV_HEADER_MAGIC: u32 = 0x07230203;
pub const SPV_HEADER_MAGIC_NUM_OFFSET: usize = 0;
pub const SPV_HEADER_INSTRUCTION_BOUND_OFFSET: usize = 3;

pub const SPV_INSTRUCTION_OP_NOP: u16 = 1;
pub const SPV_INSTRUCTION_OP_TYPE_VOID: u16 = 19;
pub const SPV_INSTRUCTION_OP_TYPE_IMAGE: u16 = 25;
pub const SPV_INSTRUCTION_OP_TYPE_SAMPLER: u16 = 26;
pub const SPV_INSTRUCTION_OP_TYPE_SAMPLED_IMAGE: u16 = 27;
pub const SPV_INSTRUCTION_OP_TYPE_POINTER: u16 = 32;
pub const SPV_INSTRUCTION_OP_TYPE_FUNCTION: u16 = 33;
pub const SPV_INSTRUCTION_OP_FUNCTION_PARAMTER: u16 = 55;
pub const SPV_INSTRUCTION_OP_FUNCTION_CALL: u16 = 57;
pub const SPV_INSTRUCTION_OP_VARIABLE: u16 = 59;
pub const SPV_INSTRUCTION_OP_LOAD: u16 = 61;
pub const SPV_INSTRUCTION_OP_DECORATE: u16 = 71;
pub const SPV_INSTRUCTION_OP_SAMPLED_IMAGE: u16 = 86;

pub const SPV_STORAGE_CLASS_UNIFORM_CONSTANT: u32 = 0;
pub const SPV_DECORATION_BINDING: u32 = 33;
pub const SPV_DECORATION_DESCRIPTOR_SET: u32 = 34;
